### ISSUE TITLE
Certificates

### ISSUE THREAD

**Issue by codyloyd** [TheOdinProject/discussions#2]
We have been dancing around this topic for a _looong_ time.  I'm just going to present what I think about the idea of offering certificates and let anyone else chime in.

I think the certificates themselves are pointless.  As an employer I am not going to be impressed by a student having collected any number of certificates from free online courses, and I might even be tempted to look down upon an applicant who thought it was a good idea to include them in a resume.

However, if offering a certificate is going to bring in more students and or motivate them then it _may_ be a good idea anyway.

My main issue with them is that if we're going to do it they _neeeed_ to be meaningful, which is difficult considering the flexible nature of our course.  

My suggestion:

In order to earn a 'certificate' a student must submit a web-portfolio with a specific number of projects (5?) that show proficiency in each of the curriculum goals => Ruby/Rails/JS/CSS

We should have specific criteria that we're looking for to make it easy for students to know what they have to do and to make it easier for reviewers to judge the portfolio.

Portfolios don't _neeed_ to be made up of the final projects of every section, but that's highly recommended... there should be some obvious way of knowing whether the student has done Odin, or if they've just cobbled together stuff they've been working on outside of it... so like if they do ALL of the Ruby/Rails sections and submit their odinbook and chess, I wouldn't really care if they just submitted one of the earlier JS projects or a side-project.  In any case we'd have to come up with specific guidelines.

**Comment by mindovermiles262** [comment]
(I can't believe I'm about to write this)

We need certificates.

People looking to learn web development **want these certificates**. Look at all the beginner portfolios out there that display certificates.

I also agree with the need for said certificates to be meaningful.  In addition to @codyloyd's suggestion RE: x number of projects, we should have criteria for project submissions, contributions, and/or lesson completion

**Comment by codyloyd** [comment]
> RE: x number of projects, we should have criteria for project submissions, contributions, and/or lesson completion

Agree.  My main point is that I don't think we should require 100% completion of Odin... but we do need some criteria outside of simply the portfolio.  This will be easier to track once we change how project submissions are handled, but something like 90-95% project submission (not lesson completion!) seems appropriate.

this will also have to change at whatever point we introduce diverging tracks to the curriculum.

**Comment by CouchofTomato** [comment]
Initially I was all for this because they're an easy sell but after listening to what everyone was saying I'm no longer sure. It's easy for other sites to offer a certificate because all of their testing is done on their site under controlled conditions so you need to pass those tests to pass the course. Easy to issue a cert for that. If it isn't done this way then there is usually a charge for getting the certificate.

Our problem is one of consistency. For projects such as ours (which I much prefer) there is a huge amount of flexibility in how a student tackles a project so each project will need to be checked on some level for certain standards. That's a pretty huge task and if the plan is to grow Odin then that will only get worse.

I'm not sure how feasible this actually is.

@codyloyd You mention it being done by project submissions but I could submit anything, nobody checks the actual content of the submission. I could submit blank files.

I would much rather focus my efforts on improving the curriculum than checking over yet another students projects to see if everything is in order.

**Comment by codyloyd** [comment]
for what it's worth I meant project submissions + portfolio review, but what you mention about checking projects is exactly the problem.

The reason I like the portfolio is because it would at least limit the amount of stuff we have to dig through to see if they can actually code... and would allow us to set up a rubric of what exactly we're looking for.

> I would much rather focus my efforts on improving the curriculum than checking over yet another students projects to see if everything is in order.

💯

**Comment by JonathanYiv** [comment]
I definitely agree that certificates should have meaning, and I think that will be the most difficult part to implement successfully.

The most important things are that it needs to be 'cheap,' meaning it doesn't waste valuable contributor time, and 'effective' aka your mama can't get a certificate overnight by cloning another student's repositories. The challenges going forward are like what @CouchofTomato said, projects aren't done in a closed and controlled environment.

> I would much rather focus my efforts on improving the curriculum than checking over yet another students projects to see if everything is in order.

I also think contributors shouldn't be forced into a grading position. That's just thankless volunteer work.

Some brainstorming:
# 1) Crowd-Sourced Grading
[Khan Academy](http://www.khanacademy.org) has a crowd-sourced mechanism wherein students who complete projects must grade two other projects based on a rubric. A similar system could be that a student two projects ahead must grade two projects behind them. This way a more experienced student takes whatever they've learned going forward, and passes it on. 

**Pros:** This removes the weight off of the contributors entirely, long term. Obviously, we would need some initial investment to get the system going, but as the number of students increase, the less work will be needed. This also gives valuable learning experience to many of the students in working with each other, giving and receiving constructive feedback, and navigating GitHub's site for creating issues/PRs/etc.

**Cons:** This type of system would require a lot of work to create. We would also have to write rubrics in accord with each project. Students can be unreliable. They may not follow the grading rubric strictly, or lazily evaluate just to progress on Odin. It also adds another barrier to them progressing (although we could make this system optional -- only those who want a certificate could participate). This means that a final check at the end of each section or at the end of the curriculum to verify a student is using original work and didn't get shoddy acceptance grades may be required -- which is manpower. But from what I can see, very few make it that far.

# 2) Automated Testing

Like exercism.io, we could have a tests scripts written for each project, and then run each project through them through some sort of automated process in the project submission action.

**Pros:** This requires the least human work and set-up.

**Cons:** Someone could just copy someone else's repository (unless there was some way to compare repos with a test?). This narrows the possible permutations of completing a project and moves closer towards the 'controlled' environment world. 

# 3) Checking everything by hand

lolno

**Comment by CouchofTomato** [comment]
Hi @JonathanYiv. You've got some great suggestions. Appreciate the time you've given to provide some feedback.

I think ultimately though this is for certificates. Those are pretty big changes required for something that we aren't even all on board with.

I think maybe we're all getting a bit carried away. We're all agreed that nobody is going to get a job because they have an Odin certificate and ultimately it'll be their portfolio and networking that'll do it. Therefore, if we do implemented certs, maybe we can just award a certificate for those that have completed x amount of TOP or if they submit a portfolio of their work completed from TOP projects. Ultimately they're only cheating themselves if they don't do the required work themselves because they'd get found out pretty quickly in a job even if they did get a foot in the door. We can always revise that approach if we get some angry emails from employers who hired people just because of their TOP certificate.

**Comment by mindovermiles262** [comment]
> 3) Checking everything by hand
> lolno

How many people do we expect to complete the course? MAYBE (??) one a week?  Doing by hand wouldn't be SUCH a bad idea until we need to worry about scaling
