### ISSUE TITLE
Forums

### ISSUE THREAD

**Issue by CouchofTomato** [TheOdinProject/discussions#3]
We might as well split out some of our more serious considerations to new issues so that they can be discussed and now buried under a larger thread full of lots of issues.

Here we can discuss the proposal to introduce forums.

What are peoples thoughts?

Gitter does support forum type places if you click on the more Odin rooms button it will show there are current 3. They title them as topics. The benefit is they are in the same place as gitter, the downside is they aren't well advertised and I'm not sure they support tagging etc so we might want to consider alternatives if we want something with more options.

**Comment by codyloyd** [comment]
from @JonathanYiv
> In that sense, we wouldn't lose chat members because they probably prefer chatting. Instead, we would gain huge value because there is a huge silent majority of the community.

I agree with this.

about the Gitter forums => the visibility of them is miserable. :( maybe we could find a way to use them more effectively??

AAAAND I've never used discourse at all, but if it's ezpz to set up and use why not give it a shot?

**Comment by JonathanYiv** [comment]
Gitter forums look ugly /=
Discourse looks shmexy

**Comment by KevinMulhern** [comment]
I get emails about new posts in the forum, but thats about as much visibility as I get with them. The UI is pretty terrible too. 

I think we should use discourse as well, its easy to set up as Cody mentioned and its a ruby app so we can customize it however we wish.

**Comment by JonathanYiv** [comment]
[Moving this here to keep the other thread focused]

There's a lot to read and think about, but I want to reply for now mostly about the forum, which you may have noticed I listed as number 1 for bestest thingy.

I want to make a case for it being the next big feature.

You both mentioned that perhaps the forum might divide the community between the forum and chat room.
From my experience in online communities (mostly gaming admittedly), there are forum users who never would use chat, chat users who would never use the forums, and power users who participate in both.
In that sense, we wouldn't lose chat members because they probably prefer chatting. Instead, we would gain huge value because there is a huge silent majority of the community.

I mentioned this briefly earlier, but it opens up room for so many things.
A) Long-Term Introductions
Right now, if a new person enters the chat, and I'm not there, I'm not going to purposefully engage with that person until they randomly appear later.
They simply disappear, and if they mention having a background in something I am interested in, I'm not going to have the opportunity to reply "Hey, you like ___? Blah blah blah."
Then they get a notification or something and respond back.

B) Documentation
Like I said earlier, common issues with the curriculum will be documented because, well, people like to complain. So they will complain, and we can reference this as a useful form of user feedback to improve.
As beginners, GitHub, issues, and PRs are probably unfamiliar to them, whereas they may have had forum experience and can more easily communicate through it.

C) Suggestions
I'd like to take this repository itself as an example.
We clearly needed a way to discuss important things, scroll back and reference our discussion, think about it, and reply.
So here we are, and I don't think a GitHub repo using issues is the most accessible zone for the normal user.
Chat simply can't offer this functionality either.

D) Discussion
Building on point C, there is simply no means of long-term discussion that is preserved.
Odin has lessons that change infrequently.
A subforum for each lesson and project would enable discussion beyond the chat.
Each lesson has "Discuss this in the Chat!"
If I went into chat right now and said, "I finished APIs tonight and thought this was cool!"
I miiiight get one or two replies.
In a forum, the replies would come slower, but there would be more of them long-term.

<hr>

Those are just a few of the benefits that a forum would bring that the chat cannot.

Lastly, on the topic of moderators. It's certainly a thankless job, but also an invaluable one.

I will volunteer as an initial moderator; I've had experience doing so.

I'm confident that people will naturally rise to the role with time, allowing me to step away later on if I need/want to. People like contributing. People like being important. People like helping.

PS: I also want to help implement the forum if we're gonna do it..

**Comment by JonathanYiv** [comment]
I'm going to start looking into Discourse later this week, and playing around with it. I'll share the results/reflections

**Comment by JonathanYiv** [comment]
So I've got it downloaded and stuff and it's neat.

Let's talking hosting tho.
They have this cool [tutorial](https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md) for deploying it via Docker to a cloud server.

Some options are:
[Digital Ocean](https://www.digitalocean.com/products/one-click-apps/discourse/) which has the lowest price at $5/month and is recommended by Discourse.
[Heroku](https://github.com/heroku/discussion/blob/master/docs/install-HEROKU.md) which looks like at least $44/month.
[Discourse](https://payments.discourse.org/pricing) itself offers the most expensive tier with $100 monthly for their standard plan.

This [discourse discussion thread](https://meta.discourse.org/t/the-cheapest-solution-for-hosting/24060/28) discusses some of cheapest options as well -- some of them sound obscure

**Comment by KevinMulhern** [comment]
Thanks for all your research into this @JonathanYiv 😄 

Memory is my main concern with the forum, I think we will need 2gb to be safe with traffic spikes and being able to handle a lot of concurrent users.

**Comment by JonathanYiv** [comment]
With that, this is one of the cheapest options I have found: [OVH](https://www.ovh.com/us/vps/vps-ssd.xml) 
at $3.35/month

**Comment by KevinMulhern** [comment]
I'd be very tempted to go with digital ocean, $20 a month for 2 gigs of memory is awesome. In comparison we are spending about $50 a month for 1gb to run the main site.

**Comment by JonathanYiv** [comment]
I agree. I'm feeling the bias towards Digital Ocean as the best price point and brand name power

**Comment by ryanford** [comment]
Vultr is 2.50/mo with the same specs as DO's $5/mo.
